use clap::ValueEnum;

#[derive(Debug, Clone, Copy, ValueEnum)]
pub enum LanguageCode {
    Ace,
    AceArab,
    Af,
    Am,
    An,
    Ar,
    Ary,
    Arz,
    As,
    Az,
    Ba,
    Ban,
    Bar,
    Be,
    Bg,
    Bho,
    Bjn,
    BjnArab,
    Bm,
    Bn,
    Br,
    Bs,
    Bug,
    Ca,
    Ceb,
    CrhLatn,
    Cs,
    Cy,
    Da,
    De,
    Din,
    Dv,
    Dz,
    El,
    En,
    EnXxSimple,
    Eo,
    Es,
    Et,
    Eu,
    Fa,
    Fi,
    Fil,
    Fo,
    Fr,
    FrCA,
    FrCa,
    Fur,
    Fuv,
    Fy,
    Ga,
    Gd,
    Gl,
    Gn,
    Gu,
    Ha,
    He,
    Hi,
    Hne,
    Hr,
    Hu,
    Hy,
    Id,
    Ig,
    Io,
    Is,
    It,
    Iu,
    Ja,
    Jv,
    Ka,
    Kk,
    Km,
    Kn,
    Ko,
    Kr,
    KrArab,
    Ks,
    KsDeva,
    Ku,
    Ky,
    La,
    Lb,
    Li,
    Lij,
    Lmo,
    Lt,
    Ltg,
    Lv,
    Mag,
    Mg,
    Mi,
    Mk,
    Ml,
    Mn,
    Mni,
    Mr,
    Ms,
    Mt,
    Mwl,
    My,
    Nb,
    Nds,
    NdsNL,
    NdsNl,
    Ne,
    Nl,
    Nn,
    No,
    Nus,
    Oc,
    Or,
    Pa,
    Pl,
    Prs,
    Ps,
    Pt,
    PtBr,
    Ro,
    Ru,
    Rw,
    Sc,
    Scn,
    Sd,
    Se,
    Sh,
    Shn,
    Si,
    Simple,
    Sk,
    Sl,
    So,
    Sq,
    Sr,
    Sv,
    Sw,
    Szl,
    Ta,
    Taq,
    TaqTfng,
    Te,
    Tg,
    Th,
    Tk,
    Tl,
    Tr,
    Tt,
    Tzm,
    Ug,
    Uk,
    Ur,
    Uz,
    Vec,
    Vi,
    Wa,
    Wuu,
    Xh,
    Yi,
    Yo,
    Zh,
    ZhHant,
    ZhCn,
    ZhTw,
    Zu,
}

impl LanguageCode {
    /// Convert to token
    pub fn to_token(&self) -> &str {
        match self {
            LanguageCode::Ace => "ace",
            LanguageCode::AceArab => "ace_Arab",
            LanguageCode::Af => "af",
            LanguageCode::Am => "am",
            LanguageCode::An => "an",
            LanguageCode::Ar => "ar",
            LanguageCode::Ary => "ary",
            LanguageCode::Arz => "arz",
            LanguageCode::As => "as",
            LanguageCode::Az => "az",
            LanguageCode::Ba => "ba",
            LanguageCode::Ban => "ban",
            LanguageCode::Bar => "bar",
            LanguageCode::Be => "be",
            LanguageCode::Bg => "bg",
            LanguageCode::Bho => "bho",
            LanguageCode::Bjn => "bjn",
            LanguageCode::BjnArab => "bjn_Arab",
            LanguageCode::Bm => "bm",
            LanguageCode::Bn => "bn",
            LanguageCode::Br => "br",
            LanguageCode::Bs => "bs",
            LanguageCode::Bug => "bug",
            LanguageCode::Ca => "ca",
            LanguageCode::Ceb => "ceb",
            LanguageCode::CrhLatn => "crh_Latn",
            LanguageCode::Cs => "cs",
            LanguageCode::Cy => "cy",
            LanguageCode::Da => "da",
            LanguageCode::De => "de",
            LanguageCode::Din => "din",
            LanguageCode::Dv => "dv",
            LanguageCode::Dz => "dz",
            LanguageCode::El => "el",
            LanguageCode::En => "en",
            LanguageCode::EnXxSimple => "en_xx_simple",
            LanguageCode::Eo => "eo",
            LanguageCode::Es => "es",
            LanguageCode::Et => "et",
            LanguageCode::Eu => "eu",
            LanguageCode::Fa => "fa",
            LanguageCode::Fi => "fi",
            LanguageCode::Fil => "fil",
            LanguageCode::Fo => "fo",
            LanguageCode::Fr => "fr",
            LanguageCode::FrCA => "fr_CA",
            LanguageCode::FrCa => "fr_ca",
            LanguageCode::Fur => "fur",
            LanguageCode::Fuv => "fuv",
            LanguageCode::Fy => "fy",
            LanguageCode::Ga => "ga",
            LanguageCode::Gd => "gd",
            LanguageCode::Gl => "gl",
            LanguageCode::Gn => "gn",
            LanguageCode::Gu => "gu",
            LanguageCode::Ha => "ha",
            LanguageCode::He => "he",
            LanguageCode::Hi => "hi",
            LanguageCode::Hne => "hne",
            LanguageCode::Hr => "hr",
            LanguageCode::Hu => "hu",
            LanguageCode::Hy => "hy",
            LanguageCode::Id => "id",
            LanguageCode::Ig => "ig",
            LanguageCode::Io => "io",
            LanguageCode::Is => "is",
            LanguageCode::It => "it",
            LanguageCode::Iu => "iu",
            LanguageCode::Ja => "ja",
            LanguageCode::Jv => "jv",
            LanguageCode::Ka => "ka",
            LanguageCode::Kk => "kk",
            LanguageCode::Km => "km",
            LanguageCode::Kn => "kn",
            LanguageCode::Ko => "ko",
            LanguageCode::Kr => "kr",
            LanguageCode::KrArab => "kr_Arab",
            LanguageCode::Ks => "ks",
            LanguageCode::KsDeva => "ks_Deva",
            LanguageCode::Ku => "ku",
            LanguageCode::Ky => "ky",
            LanguageCode::La => "la",
            LanguageCode::Lb => "lb",
            LanguageCode::Li => "li",
            LanguageCode::Lij => "lij",
            LanguageCode::Lmo => "lmo",
            LanguageCode::Lt => "lt",
            LanguageCode::Ltg => "ltg",
            LanguageCode::Lv => "lv",
            LanguageCode::Mag => "mag",
            LanguageCode::Mg => "mg",
            LanguageCode::Mi => "mi",
            LanguageCode::Mk => "mk",
            LanguageCode::Ml => "ml",
            LanguageCode::Mn => "mn",
            LanguageCode::Mni => "mni",
            LanguageCode::Mr => "mr",
            LanguageCode::Ms => "ms",
            LanguageCode::Mt => "mt",
            LanguageCode::Mwl => "mwl",
            LanguageCode::My => "my",
            LanguageCode::Nb => "nb",
            LanguageCode::Nds => "nds",
            LanguageCode::NdsNL => "nds_NL",
            LanguageCode::NdsNl => "nds_nl",
            LanguageCode::Ne => "ne",
            LanguageCode::Nl => "nl",
            LanguageCode::Nn => "nn",
            LanguageCode::No => "no",
            LanguageCode::Nus => "nus",
            LanguageCode::Oc => "oc",
            LanguageCode::Or => "or",
            LanguageCode::Pa => "pa",
            LanguageCode::Pl => "pl",
            LanguageCode::Prs => "prs",
            LanguageCode::Ps => "ps",
            LanguageCode::Pt => "pt",
            LanguageCode::PtBr => "pt_br",
            LanguageCode::Ro => "ro",
            LanguageCode::Ru => "ru",
            LanguageCode::Rw => "rw",
            LanguageCode::Sc => "sc",
            LanguageCode::Scn => "scn",
            LanguageCode::Sd => "sd",
            LanguageCode::Se => "se",
            LanguageCode::Sh => "sh",
            LanguageCode::Shn => "shn",
            LanguageCode::Si => "si",
            LanguageCode::Simple => "simple",
            LanguageCode::Sk => "sk",
            LanguageCode::Sl => "sl",
            LanguageCode::So => "so",
            LanguageCode::Sq => "sq",
            LanguageCode::Sr => "sr",
            LanguageCode::Sv => "sv",
            LanguageCode::Sw => "sw",
            LanguageCode::Szl => "szl",
            LanguageCode::Ta => "ta",
            LanguageCode::Taq => "taq",
            LanguageCode::TaqTfng => "taq_Tfng",
            LanguageCode::Te => "te",
            LanguageCode::Tg => "tg",
            LanguageCode::Th => "th",
            LanguageCode::Tk => "tk",
            LanguageCode::Tl => "tl",
            LanguageCode::Tr => "tr",
            LanguageCode::Tt => "tt",
            LanguageCode::Tzm => "tzm",
            LanguageCode::Ug => "ug",
            LanguageCode::Uk => "uk",
            LanguageCode::Ur => "ur",
            LanguageCode::Uz => "uz",
            LanguageCode::Vec => "vec",
            LanguageCode::Vi => "vi",
            LanguageCode::Wa => "wa",
            LanguageCode::Wuu => "wuu",
            LanguageCode::Xh => "xh",
            LanguageCode::Yi => "yi",
            LanguageCode::Yo => "yo",
            LanguageCode::Zh => "zh",
            LanguageCode::ZhHant => "zh_Hant",
            LanguageCode::ZhCn => "zh_cn",
            LanguageCode::ZhTw => "zh_tw",
            LanguageCode::Zu => "zu",
        }
    }
}
